'use strict';

const fs = require('node:fs');
const path = require('node:path');

/**
 * DSH plugin ids disabled by the VS Code embed overlay. The embedded webview
 * already provides the sidebar and the AION UI panel, so launching the managed
 * DSH server with these plugins active would duplicate both surfaces.
 * @type {readonly string[]}
 */
const EMBED_DISABLED_PLUGIN_IDS = Object.freeze([
  'better-sidebar',
  'ui-dsh-aionui-panel',
]);

/**
 * Render the embed overlay document consumed by `dsh --patch <path>`.
 * The content is built exclusively from the frozen id constant above; no
 * caller input is ever interpolated into it.
 * @returns {string} overlay YAML with two `#` comment lines and one entry per
 *   disabled plugin, terminated by a single `\n`.
 */
function renderEmbedOverlay() {
  const lines = [
    '# VS Code embed overlay, generated by dsh-vs-sidebar.',
    '# Disables DSH plugins that would duplicate the embedded VS Code sidebar/panel.',
  ];
  for (const id of EMBED_DISABLED_PLUGIN_IDS) {
    lines.push(`- id: ${id}`, '  disabled: true');
  }
  return `${lines.join('\n')}\n`;
}

/**
 * Write the embed overlay file into `directory` and return its absolute path.
 * @param {string} directory non-empty absolute directory that will receive
 *   `vscode-embed.overlay.yml`; created recursively when missing.
 * @param {{ writeFileSync?: typeof fs.writeFileSync, mkdirSync?: typeof fs.mkdirSync }} [options]
 *   injectable fs operations for tests.
 * @returns {string} absolute path of the written overlay file.
 */
function writeEmbedOverlay(directory, options = {}) {
  if (typeof directory !== 'string' || directory.length === 0 || !path.isAbsolute(directory)) {
    throw new Error('embed overlay directory must be a non-empty absolute path');
  }
  const {
    writeFileSync = fs.writeFileSync,
    mkdirSync = fs.mkdirSync,
  } = options || {};
  mkdirSync(directory, { recursive: true });
  const overlayPath = path.join(directory, 'vscode-embed.overlay.yml');
  writeFileSync(overlayPath, renderEmbedOverlay(), 'utf8');
  return overlayPath;
}

module.exports = {
  EMBED_DISABLED_PLUGIN_IDS,
  renderEmbedOverlay,
  writeEmbedOverlay,
};
